@URL=http://localhost:8000

GET {{URL}}

###

GET {{URL}}/api/posts
Accept: application/json

###

POST {{URL}}/api/posts
Accept: application/json
Content-Type: application/json

{
  "title": "Hello",
  "content": "World"
}

###

GET {{URL}}/api/posts/1
Accept: application/json