version: "3.8"
services:
  server:
    #image: 'nginx:stable-alpine'
    build:
      context: . # current directory so we can use path relative to current directory inside a dockerfile
      dockerfile: dockerfiles/nginx.dockerfile
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html:delegated # delegated option is used to improve performance (make code modifications in batchs)
  mysql:
    image: "mysql:8.4"
    container_name: mysql
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    container_name: composer
    volumes:
      - ./src:/var/www/html
  artisan:
    container_name: artisan
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: "node:14"
    container_name: npm
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html
