apiVersion: v1
kind: Service
metadata:
  name: laravel-app
spec:
  selector:
    app: laravel-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: laravel-app
          image: 038504125973.dkr.ecr.us-east-1.amazonaws.com/ilaravel-deploy:latest
          imagePullPolicy: Always