name: Tests

on: workflow_dispatch

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Authenticate to AWS
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          role-session-name: ${{ github.run_id }}
          aws-region: ${{ vars.AWS_REGION }}

      # For real or production project, use SSM and/or Parameter Store to set up environment variables
      - name: Set up environment variables
        run: |
          aws s3 cp ${{ secrets.S3_BUCKET_URI_ENV_FILE }} src/.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Build image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: dockerfiles/php.dockerfile
      #     tags: ilaravel-deploy:${{ github.sha }}-testing

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Installing dependencies
        run: /usr/bin/docker compose run --rm composer install

      - name: Running tests
        run: /usr/bin/docker compose run --rm artisan test

      # - name: Testing
      #   run: |
      #     php /var/www/html/artisan test
