name: Tests

on: workflow_dispatch

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Build image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: dockerfiles/php.dockerfile
      #     tags: ilaravel-deploy:${{ github.sha }}-testing

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Running tests
        run: /usr/bin/docker compose run --rm artisan test

      # - name: Testing
      #   run: |
      #     php /var/www/html/artisan test
